import { Injectable } from "@nestjs/common";
import { readInboundVerdicts } from "../../../capabilities/mailbox/inbound/spam-verdict.js";
import type { ReplyDecision, ReplyDecisionInput, ReplyDecisionProvider } from "./reply-decision.js";

/**
 * The rules Eva decides by today (slice 3.1c-2, founder ruling 54 — no AI yet).
 *
 * 🚨 THE ONE THING THIS FILE EXISTS TO PREVENT IS A MAIL LOOP.
 *
 * Eva replies **from the customer's own mailbox**. If she answers an
 * auto-responder, that machine answers her, and she answers it again — a loop
 * running on the CUSTOMER'S domain, in the CUSTOMER'S name, at the customer's
 * reputation. It would not look like our bug to anybody involved. Every rule
 * under "never" below is a documented way of saying "a machine sent this", and
 * they are checked before anything else.
 *
 * ⚠️ THE HEADERS ARE NOT GUESSES; MOST ARE STANDARDS.
 *   - `Auto-Submitted` — RFC 3834 §5, the header that exists precisely so
 *     automatic responders can avoid answering each other.
 *   - `List-Id` / `List-Unsubscribe` — RFC 2919 / RFC 8058, mailing list mail.
 *   - `Precedence: bulk|list|junk` — not a standard but near-universal, and
 *     what most auto-responders have honoured for thirty years.
 *   - `X-Auto-Response-Suppress` — Microsoft's, and the one Outlook itself
 *     sets on delivery reports and out-of-office notices.
 *
 * ⚠️ ORDER MATTERS AND IT IS NOT ARBITRARY. "never" is evaluated before
 * "hold": a bounce message that also carries an uncertain spam verdict must be
 * refused outright, not parked for a human to make a judgement nobody should
 * be asked to make.
 */

/**
 * Local parts that are, by convention, unattended. Matched on the whole local
 * part or as a prefix before a separator, never as a substring — `enquiries@`
 * contains "que" and `noreply` does not appear in it, but a naive `includes`
 * on a longer list is exactly how a real address gets caught.
 */
const UNATTENDED_LOCAL_PARTS = [
  "noreply",
  "no-reply",
  "no_reply",
  "donotreply",
  "do-not-reply",
  "do_not_reply",
  "mailer-daemon",
  "postmaster",
  "bounce",
  "bounces",
];

/**
 * ⚠️ NOT `automatic-reply` OR `out of office` IN THE SUBJECT. A subject line is
 * attacker-controlled and, worse, ordinary: "Re: out of office cover — can you
 * quote?" is a real enquiry from a real person. Every rule here reads a header
 * a machine sets about itself, which is the only signal that means what it says.
 */

interface Rule {
  signal: string;
  reason: string;
  applies(input: ReplyDecisionInput): boolean;
}

function header(headers: Record<string, string>, name: string): string | undefined {
  const direct = headers[name];
  if (direct !== undefined) return direct;
  // Casing must not silently disable a rule — the `spam-verdict.ts` lesson.
  const found = Object.entries(headers).find(([key]) => key.toLowerCase() === name);
  return found?.[1];
}

function has(headers: Record<string, string>, name: string): boolean {
  const value = header(headers, name);
  return value !== undefined && value.trim() !== "";
}

function localPartOf(address: string): string {
  const at = address.lastIndexOf("@");
  const local = at === -1 ? address : address.slice(0, at);
  return local.trim().toLowerCase().replace(/^"|"$/g, "");
}

/**
 * Refusals, in the order they are checked. Each one names a machine.
 */
const NEVER_RULES: Rule[] = [
  {
    signal: "auto-submitted",
    // RFC 3834: anything other than "no" means generated by an automatic process.
    reason: "it was sent automatically by another system, so answering it could start a loop",
    applies: ({ headers }) => {
      const value = header(headers, "auto-submitted");
      if (value === undefined) return false;
      return value.trim().toLowerCase() !== "no";
    },
  },
  {
    signal: "precedence-bulk",
    reason: "it is marked as bulk or list mail rather than a personal message",
    applies: ({ headers }) => {
      const value = header(headers, "precedence")?.trim().toLowerCase();
      return value === "bulk" || value === "list" || value === "junk" || value === "auto_reply";
    },
  },
  {
    signal: "mailing-list",
    reason: "it came from a mailing list rather than from a person",
    applies: ({ headers }) => has(headers, "list-id") || has(headers, "list-unsubscribe"),
  },
  {
    signal: "auto-response-suppressed",
    reason: "the sending system asked not to receive automatic replies",
    applies: ({ headers }) => has(headers, "x-auto-response-suppress"),
  },
  {
    /**
     * ⚠️ AN EMPTY RETURN-PATH IS THE BOUNCE SIGNAL, AND `<>` IS NOT A TYPO.
     * RFC 5321 requires a null reverse-path on delivery status notifications
     * precisely so that answering one cannot bounce in turn. Replying to a
     * bounce is the purest form of the loop this file prevents.
     */
    signal: "bounce",
    reason: "it is a delivery failure notice, not an enquiry",
    applies: ({ headers }) => {
      const path = header(headers, "return-path")?.trim();
      if (path === "<>" || path === "") return true;
      const type = header(headers, "content-type")?.toLowerCase() ?? "";
      return type.includes("multipart/report");
    },
  },
  {
    signal: "unattended-sender",
    reason: "it came from an address that does not accept replies",
    applies: ({ fromAddress }) => {
      const local = localPartOf(fromAddress);
      return UNATTENDED_LOCAL_PARTS.some(
        (unattended) =>
          local === unattended ||
          local.startsWith(`${unattended}-`) ||
          local.startsWith(`${unattended}.`) ||
          local.startsWith(`${unattended}_`),
      );
    },
  },
  {
    /**
     * ⚠️ NO ADDRESS MEANS NO REPLY, AND IT IS "never", NOT "hold". A human
     * reviewing it could not send one either — there is nowhere for it to go.
     * Parking it in a queue would ask somebody to make a decision that has no
     * available answer.
     */
    signal: "no-reply-address",
    reason: "there is no address to reply to",
    applies: ({ fromAddress }) => !fromAddress.includes("@") || fromAddress.trim() === "",
  },
];

@Injectable()
export class RuleBasedReplyDecisionProvider implements ReplyDecisionProvider {
  decide(input: ReplyDecisionInput): ReplyDecision {
    for (const rule of NEVER_RULES) {
      if (rule.applies(input)) {
        return { verdict: "never", reason: rule.reason, signal: rule.signal };
      }
    }

    /**
     * ⚠️ THE UNCERTAIN MIDDLE, AND IT IS EXACTLY WHAT RULING 32 DESCRIBES.
     * Intake lets `GRAY` through on purpose — SES said "probably spam, not
     * certain", and binning those would silently lose real enquiries. So the
     * lead exists, and the question lands here: Eva does not answer it on her
     * own, and it waits in the book for a person.
     *
     * ⚠️ `PROCESSING_FAILED` AND `UNKNOWN` HOLD TOO, AND THAT IS THE
     * FAIL-CLOSED DIRECTION. Both mean "nobody scanned this" — a missing
     * header included. Treating "I don't know" as "it's fine" is how an
     * automatic reply goes out to something nothing ever checked.
     */
    const { spam } = readInboundVerdicts(input.headers);
    if (spam !== "PASS") {
      return {
        verdict: "hold",
        reason:
          spam === "GRAY"
            ? "it might be junk, so Eva left it for you to read first"
            : "it could not be checked for junk, so Eva left it for you to read first",
        signal: `spam-verdict-${spam.toLowerCase()}`,
      };
    }

    return {
      verdict: "reply",
      reason: "it looks like a person asking about work",
      signal: "no-refusal",
    };
  }
}
